# Generated by Django 3.2.25 on 2025-03-13 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FixedVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_at', models.DateTimeField(auto_now_add=True)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vulnerabilities.vulnerability')),
            ],
        ),
    ]
